<a href="https://colab.research.google.com/github/pradee1/deep_learning/blob/master/Multi_class_classification_Keras_tf(MNIST).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classifying Handwritten Digits with Neural Networks

![img](https://www.tensorflow.org/versions/r0.11/images/MNIST.png)

**Learning Objectives:**
  * Train a neural network to classify handwritten digits from the classic [MNIST](http://yann.lecun.com/exdb/mnist/) data set using keras and tensorflow
  * Visualize the weights of a neural-network hidden layer

In [0]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd

In [0]:
mnist_dataframe = pd.read_csv(
  "https://download.mlcc.google.com/mledu-datasets/mnist_train_small.csv",
  sep=",",
  header=None)

In [3]:
mnist_dataframe.head()

0    1    2    3    4    5    6    ...  778  779  780  781  782  783  784
0    6    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1    5    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2    7    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3    9    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4    5    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[5 rows x 785 columns]

In [4]:
from keras.layers import Input, Dense
from keras.models import Model
from keras.utils import to_categorical

Using TensorFlow backend.


In [5]:
# This returns a tensor
inputs = Input(shape=(784,))

# a layer instance is callable on a tensor, and returns a tensor
x = Dense(128, activation='relu')(inputs)
x = Dense(128, activation='relu')(x)
x = Dense(64, activation='relu')(x)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

my_model = Model(inputs=inputs, outputs= predictions)
my_model.compile(optimizer='adam',loss='categorical_crossentropy',
                 metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [6]:
my_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               100480    
_________________________________________________________________
dense_2 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_3 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_4 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_5 (Dense)              (None, 10)                650       
Total params: 130,058
Trainable params: 130,058
Non-trainable params: 0
_________________________________________________________________


In [0]:
x = np.array(mnist_dataframe.drop(0,axis=1))
y = np.array(mnist_dataframe[[0]])
y = to_categorical(y,num_classes=None,dtype='float32')

In [8]:
my_model.fit(x=x, y=y, batch_size=128, epochs=10,verbose=2, validation_split=0.2)

Instructions for updating:
Use tf.cast instead.
Train on 16000 samples, validate on 4000 samples
Epoch 1/10
 - 4s - loss: 7.6156 - acc: 0.5014 - val_loss: 6.7002 - val_acc: 0.5690
Epoch 2/10
 - 1s - loss: 6.6394 - acc: 0.5722 - val_loss: 6.6579 - val_acc: 0.5715
Epoch 3/10
 - 1s - loss: 6.4968 - acc: 0.5844 - val_loss: 6.5152 - val_acc: 0.5773
Epoch 4/10
 - 1s - loss: 5.0284 - acc: 0.6569 - val_loss: 2.6433 - val_acc: 0.7668
Epoch 5/10
 - 1s - loss: 1.8100 - acc: 0.8274 - val_loss: 0.5659 - val_acc: 0.8878
Epoch 6/10
 - 1s - loss: 0.3080 - acc: 0.9274 - val_loss: 0.3291 - val_acc: 0.9185
Epoch 7/10
 - 1s - loss: 0.1733 - acc: 0.9533 - val_loss: 0.3061 - val_acc: 0.9257
Epoch 8/10
 - 1s - loss: 0.1124 - acc: 0.9685 - val_loss: 0.2737 - val_acc: 0.9365
Epoch 9/10
 - 1s - loss: 0.0798 - acc: 0.9778 - val_loss: 0.2746 - val_acc: 0.9373
Epoch 10/10
 - 1s - loss: 0.0563 - acc: 0.9841 - val_loss: 0.2676 - val_acc: 0.9367


In [13]:
my_model.

False

# TensorFlow Custom Experiment

In [0]:
import tensorflow as tf
import numpy as np
import os

In [0]:
tf.enable_eager_execution()

## Load Data

In [3]:
dataset_url = "https://download.mlcc.google.com/mledu-datasets/mnist_train_small.csv"
dataset_file = tf.keras.utils.get_file(fname=os.path.basename(dataset_url),origin=dataset_url)

36528128/36523880 [==============================] - 1s 0us/step


In [4]:
dataset_file

'/root/.keras/datasets/mnist_train_small.csv'

In [5]:
!head -n5 {dataset_file}

6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,67,67,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,252,252,66,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,159,250,232,30,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,222,252,108,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,147,252,183,5,0,0,0,0,0,0,0,20,89,89,73,0,0,0,0,0,0,0,0,0,0,0,0,48,247,252,159,0,0,0,0,0,0,0,79,236,252,252,249,198,16,0,0,0,0,0,0,0,0,0,41,193,252,199,22,0,0,0,0,0,12,135,248,252,252,252,252,252,100,0,0,0,0,0,0,0,0,0,100,252,252,88,0,0,0,0,0,11,171,252,252,235,175,178,252,252,224,0,0,0,0,0,0,0,0,15,209,252,233,12,0,0,0,0,49,177,252,252,89,26,0,2,166,252,252,0,0,0,0,0,0,0,0,96,253,253,59,0,0,0,0,11,177,255,253,92,0,0,0,0,155,253,128,0,0,0,0,0,0,0,0,143,252,252,10,0,0,0,12,171,252,216,110,13,0,0,0,3,180,

In [0]:
column_names = list(range(785))
feature_names = column_names[1:]
label_name = 0

In [0]:
batch_size = 64

training_dataset = tf.data.experimental.make_csv_dataset(dataset_file,batch_size,
                                                    column_names = column_names,
                                                    label_name = label_name,
                                                    shuffle_seed = 42,
                                                   num_epochs=1)

In [8]:
features, labels = next(iter(training_dataset))
features[1], 

Instructions for updating:
Colocations handled automatically by placer.


(<tf.Tensor: id=2410, shape=(64,), dtype=int32, numpy=
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int32)>,)

In [0]:
def pack_features_vector(features, labels):
  """Pack the features into a single array."""
  features = tf.cast(tf.stack(list(features.values()), axis=1),dtype=tf.float32)
  return features, labels

In [0]:
training_dataset = training_dataset.map(pack_features_vector)

In [11]:
#
features, labels = next(iter(training_dataset))
print(features)

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


##Model: Architecture, loss and gradient descent

In [0]:
# This returns a tensor
inputs = tf.keras.layers.Input(shape=(784,))

# a layer instance is callable on a tensor, and returns a tensor
x = tf.keras.layers.Dense(128, activation='relu',)(inputs)
x = tf.keras.layers.Dense(128, activation='relu')(x)
x = tf.keras.layers.Dense(64, activation='relu')(x)
x = tf.keras.layers.Dense(64, activation='relu')(x)
predictions = tf.keras.layers.Dense(10, activation='softmax')(x)

#my_model = tf.keras.models.Model(inputs=inputs, outputs= predictions)
model = tf.keras.models.Model(inputs=inputs, outputs= predictions)

In [14]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_3 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_4 (Dense)              (None, 10)                650       
Total params: 130,058
Trainable params: 130,058
Non-trainable params: 0
_________________________________________________________________


In [15]:
predictions = model(features)
predictions[:5]

<tf.Tensor: id=4175, shape=(5, 10), dtype=float32, numpy=
array([[2.7388835e-01, 4.7669012e-38, 4.6847821e-25, 5.2788769e-22,
        3.0230918e-13, 7.2611165e-01, 2.0363650e-18, 5.2510415e-14,
        8.5330172e-12, 4.7753484e-22],
       [3.4993367e-18, 1.1010630e-21, 3.3476856e-26, 3.9332754e-15,
        5.0863629e-32, 1.0000000e+00, 2.5433196e-18, 5.4931808e-13,
        1.5309646e-18, 2.0667135e-30],
       [1.1739925e-33, 7.6123710e-13, 5.1465142e-25, 4.7637451e-17,
        2.3715149e-38, 4.4691147e-34, 3.5774389e-29, 6.2276313e-35,
        1.0000000e+00, 0.0000000e+00],
       [4.2111958e-10, 5.4646726e-28, 1.1558102e-16, 2.0532385e-36,
        5.0985336e-28, 1.0000000e+00, 1.1642078e-33, 1.3795144e-30,
        3.3618259e-19, 5.1857999e-29],
       [8.8359653e-20, 9.1971223e-31, 1.2416200e-27, 3.3673191e-19,
        5.4608189e-20, 1.0000000e+00, 1.4939685e-22, 2.0854981e-16,
        2.4485116e-09, 2.3890442e-34]], dtype=float32)>

In [16]:
tf.nn.softmax(predictions[:5])

<tf.Tensor: id=4181, shape=(5, 10), dtype=float32, numpy=
array([[0.11553828, 0.08785728, 0.08785728, 0.08785728, 0.08785728,
        0.18160343, 0.08785728, 0.08785728, 0.08785728, 0.08785728],
       [0.08533674, 0.08533674, 0.08533674, 0.08533674, 0.08533674,
        0.23196931, 0.08533674, 0.08533674, 0.08533674, 0.08533674],
       [0.08533674, 0.08533674, 0.08533674, 0.08533674, 0.08533674,
        0.08533674, 0.08533674, 0.08533674, 0.23196931, 0.08533674],
       [0.08533674, 0.08533674, 0.08533674, 0.08533674, 0.08533674,
        0.23196931, 0.08533674, 0.08533674, 0.08533674, 0.08533674],
       [0.08533674, 0.08533674, 0.08533674, 0.08533674, 0.08533674,
        0.23196931, 0.08533674, 0.08533674, 0.08533674, 0.08533674]],
      dtype=float32)>

In [17]:
print("Prediction: {}".format(tf.argmax(predictions, axis=1)))
print("    Labels: {}".format(labels))

Prediction: [5 5 8 5 5 7 7 5 5 7 5 0 5 8 5 6 7 5 8 8 8 5 5 7 6 0 8 7 0 8 5 8 7 8 5 5 7
 0 8 8 6 5 5 7 0 5 5 8 7 2 8 3 0 5 5 8 7 2 5 7 5 7 5 6]
    Labels: [5 5 0 5 4 7 2 3 3 5 1 3 5 3 5 5 1 9 2 1 5 8 4 1 1 4 3 3 7 5 4 9 4 7 0 8 1
 5 4 7 0 0 0 8 1 1 4 2 4 2 0 7 7 5 5 6 7 3 6 8 2 3 3 3]


In [18]:
def loss(model, x, y):
  y_ = model(x)
  return tf.losses.sparse_softmax_cross_entropy(labels=y, logits=y_)


l = loss(model, features, labels)
print("Loss test: {}".format(l))

Instructions for updating:
Use tf.cast instead.
Loss test: 2.3128926753997803


In [0]:
def grad(model, inputs, targets):
  with tf.GradientTape() as tape:
    loss_value = loss(model, inputs, targets)
  return loss_value, tape.gradient(loss_value, model.trainable_variables)

In [0]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)

global_step = tf.Variable(0)

In [21]:
loss_value, grads = grad(model, features, labels)

print("Step: {}, Initial Loss: {}".format(global_step.numpy(),
                                          loss_value.numpy()))

optimizer.apply_gradients(zip(grads, model.trainable_variables), global_step)

print("Step: {},         Loss: {}".format(global_step.numpy(),
                                          loss(model, features, labels).numpy()))

Step: 0, Initial Loss: 2.3128926753997803
Step: 1,         Loss: 2.2542309761047363


In [24]:
## Note: Rerunning this cell uses the same model variables

from tensorflow import contrib
tfe = contrib.eager

# keep results for plotting
train_loss_results = []
train_accuracy_results = []

num_epochs = 201

for epoch in range(num_epochs):
  epoch_loss_avg = tfe.metrics.Mean()
  epoch_accuracy = tfe.metrics.Accuracy()

  # Training loop - using batches of 32
  for x, y in training_dataset:
    # Optimize the model
    loss_value, grads = grad(model, x, y)
    optimizer.apply_gradients(zip(grads, model.trainable_variables),
                              global_step)

    # Track progress
    epoch_loss_avg(loss_value)  # add current batch loss
    # compare predicted label to actual label
    epoch_accuracy(tf.argmax(model(x), axis=1, output_type=tf.int32), y)

  # end epoch
  train_loss_results.append(epoch_loss_avg.result())
  train_accuracy_results.append(epoch_accuracy.result())
  
  if epoch % 2 == 0:
    print("Epoch {:03d}: Loss: {:.3f}, Accuracy: {:.3%}".format(epoch,
                                                                epoch_loss_avg.result(),
                                                                epoch_accuracy.result()))

Epoch 000: Loss: 1.587, Accuracy: 87.584%
Epoch 002: Loss: 1.589, Accuracy: 87.434%
Epoch 004: Loss: 1.586, Accuracy: 87.714%
Epoch 006: Loss: 1.586, Accuracy: 87.714%
Epoch 008: Loss: 1.584, Accuracy: 87.879%
Epoch 010: Loss: 1.582, Accuracy: 88.009%
Epoch 012: Loss: 1.584, Accuracy: 87.859%
Epoch 014: Loss: 1.582, Accuracy: 87.999%
Epoch 016: Loss: 1.582, Accuracy: 88.034%
Epoch 018: Loss: 1.582, Accuracy: 88.089%
Epoch 020: Loss: 1.583, Accuracy: 88.009%


KeyboardInterrupt: ignored

In [0]:
def loss(model, features, labels):
  pred = model(features)
  return tf.losses.sparse_softmax_cross_entropy(labels=labels,logits=pred)
  

In [0]:
def gradient(model, features, labels):
  with tf.GradientTape() as tape:
    loss_value = loss(model, features, labels)

  return loss_value, tape.gradient(loss_value,model.trainable_variables)

In [0]:
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
step = tf.Variable(0)

In [33]:
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))
optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))
optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))
optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

step: 40, loss: 2.3049001693725586
step: 41, loss: 2.3049001693725586
step: 42, loss: 2.3049001693725586
step: 43, loss: 2.3049001693725586
step: 44, loss: 2.3049001693725586
step: 44, loss: 2.3049001693725586
step: 45, loss: 2.3049001693725586
step: 46, loss: 2.3049001693725586
step: 47, loss: 2.3049001693725586
step: 48, loss: 2.3049001693725586
step: 48, loss: 2.3049001693725586
step: 49, loss: 2.3049001693725586
step: 50, loss: 2.3049001693725586
step: 51, loss: 2.3049001693725586
step: 52, loss: 2.3049001693725586


## Training loop


A training loop feeds the dataset examples into the model to help it make better predictions. The following code block sets up these training steps:



1. Iterate each epoch. An epoch is one pass through the dataset.
2. Within an epoch, iterate over each example in the training Dataset grabbing its features (x) and label (y).
3. Using the example's features, make a prediction and compare it with the label. Measure the inaccuracy of the prediction and use that to calculate the model's loss and gradients.
4. Use an optimizer to update the model's variables.
5. Keep track of some stats for visualization.
Repeat for each epoch.


In [21]:
num_epochs = 100
train_loss_result = []
train_accuracy_result = []
global_step = tf.Variable(0)

for epoch in range(num_epochs):
  
  epoch_loss_avg = tf.contrib.eager.metrics.Mean()
  epoch_accuracy = tf.contrib.eager.metrics.Accuracy()

  
  for features, labels in training_dataset:
    
    train_loss, train_gradients = gradient(my_model,features,labels)
    optimizer.apply_gradients(zip(train_gradients,my_model.trainable_variables),global_step=global_step)
    
    #Track progress
    epoch_loss_avg(train_loss)
    epoch_accuracy(tf.math.argmax(my_model(features),axis=1,output_type=tf.int32),labels)
    
  #save results
  train_loss_result.append(epoch_loss_avg.result())
  train_accuracy_result.append(epoch_accuracy.result())
  
  
  if epoch%10 == 0:
    print("train_loss: {},train_accuracy: {}, epoch: {}".format(
        epoch_loss_avg.result(),
        epoch_accuracy.result(),
        epoch))

    

train_loss: 2.3731876836417203,train_accuracy: 0.08805440272013601, epoch: 0
train_loss: 2.3731876836417203,train_accuracy: 0.08805440272013601, epoch: 10


Exception ignored in: <bound method EagerResourceDeleter.__del__ of <tensorflow.python.ops.resource_variable_ops.EagerResourceDeleter object at 0x7f17cc195438>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/resource_variable_ops.py", line 139, in __del__
    self._handle, ignore_lookup_error=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_resource_variable_ops.py", line 289, in destroy_resource_op
    "ignore_lookup_error", ignore_lookup_error)
KeyboardInterrupt: 


KeyboardInterrupt: ignored