<a href="https://colab.research.google.com/github/pradee1/deep_learning/blob/master/Multi_class_classification_Keras_tf(MNIST).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classifying Handwritten Digits with Neural Networks

![img](https://www.tensorflow.org/versions/r0.11/images/MNIST.png)

**Learning Objectives:**
  * Train a neural network to classify handwritten digits from the classic [MNIST](http://yann.lecun.com/exdb/mnist/) data set using keras and tensorflow
  * Visualize the weights of a neural-network hidden layer

In [0]:
from matplotlib import pyplot as plt
import numpy as np
import pandas as pd

In [0]:
mnist_dataframe = pd.read_csv(
  "https://download.mlcc.google.com/mledu-datasets/mnist_train_small.csv",
  sep=",",
  header=None)

In [6]:
mnist_dataframe.head()

0    1    2    3    4    5    6    ...  778  779  780  781  782  783  784
0    6    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
1    5    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
2    7    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
3    9    0    0    0    0    0    0  ...    0    0    0    0    0    0    0
4    5    0    0    0    0    0    0  ...    0    0    0    0    0    0    0

[5 rows x 785 columns]

In [0]:
from keras.layers import Input, Dense
from keras.models import Model
from keras.utils import to_categorical

In [0]:
# This returns a tensor
inputs = Input(shape=(784,))

# a layer instance is callable on a tensor, and returns a tensor
x = Dense(128, activation='relu')(inputs)
x = Dense(128, activation='relu')(x)
x = Dense(64, activation='relu')(x)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

my_model = Model(inputs=inputs, outputs= predictions)
my_model.compile(optimizer='adam',loss='categorical_crossentropy',
                 metrics = ['accuracy'])

In [46]:
my_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         (None, 784)               0         
_________________________________________________________________
dense_15 (Dense)             (None, 128)               100480    
_________________________________________________________________
dense_16 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_17 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_18 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_19 (Dense)             (None, 10)                650       
Total params: 130,058
Trainable params: 130,058
Non-trainable params: 0
_________________________________________________________________


In [0]:
x = np.array(mnist_dataframe.drop(0,axis=1))
y = np.array(mnist_dataframe[[0]])
y = to_categorical(y,num_classes=None,dtype='float32')

In [48]:
my_model.fit(x=x, y=y, batch_size=128, epochs=10,verbose=2, validation_split=0.2)

Train on 16000 samples, validate on 4000 samples
Epoch 1/10
 - 2s - loss: 4.8778 - acc: 0.6441 - val_loss: 2.9303 - val_acc: 0.7710
Epoch 2/10
 - 1s - loss: 1.6122 - acc: 0.8543 - val_loss: 0.8065 - val_acc: 0.9042
Epoch 3/10
 - 1s - loss: 0.6213 - acc: 0.9179 - val_loss: 0.6667 - val_acc: 0.9100
Epoch 4/10
 - 1s - loss: 0.3795 - acc: 0.9361 - val_loss: 0.4971 - val_acc: 0.9205
Epoch 5/10
 - 1s - loss: 0.2512 - acc: 0.9511 - val_loss: 0.4977 - val_acc: 0.9175
Epoch 6/10
 - 1s - loss: 0.1950 - acc: 0.9606 - val_loss: 0.4563 - val_acc: 0.9223
Epoch 7/10
 - 1s - loss: 0.1354 - acc: 0.9702 - val_loss: 0.3726 - val_acc: 0.9327
Epoch 8/10
 - 1s - loss: 0.1062 - acc: 0.9751 - val_loss: 0.4123 - val_acc: 0.9340
Epoch 9/10
 - 1s - loss: 0.0888 - acc: 0.9789 - val_loss: 0.3445 - val_acc: 0.9380
Epoch 10/10
 - 1s - loss: 0.0723 - acc: 0.9833 - val_loss: 0.3401 - val_acc: 0.9407


# TensorFlow Custom Experiment

In [0]:
import tensorflow as tf
import numpy as np
import os

In [0]:
tf.enable_eager_execution()

## Load Data

In [0]:
dataset_url = "https://download.mlcc.google.com/mledu-datasets/mnist_train_small.csv"
dataset_file = tf.keras.utils.get_file(fname=os.path.basename(dataset_url),origin=dataset_url)

In [47]:
dataset_file

'/root/.keras/datasets/mnist_train_small.csv'

In [122]:
!head -n5 {dataset_file}

6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,67,67,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,131,252,252,66,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,159,250,232,30,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,222,252,108,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,147,252,183,5,0,0,0,0,0,0,0,20,89,89,73,0,0,0,0,0,0,0,0,0,0,0,0,48,247,252,159,0,0,0,0,0,0,0,79,236,252,252,249,198,16,0,0,0,0,0,0,0,0,0,41,193,252,199,22,0,0,0,0,0,12,135,248,252,252,252,252,252,100,0,0,0,0,0,0,0,0,0,100,252,252,88,0,0,0,0,0,11,171,252,252,235,175,178,252,252,224,0,0,0,0,0,0,0,0,15,209,252,233,12,0,0,0,0,49,177,252,252,89,26,0,2,166,252,252,0,0,0,0,0,0,0,0,96,253,253,59,0,0,0,0,11,177,255,253,92,0,0,0,0,155,253,128,0,0,0,0,0,0,0,0,143,252,252,10,0,0,0,12,171,252,216,110,13,0,0,0,3,180,

In [0]:
column_names = list(range(785))
feature_names = column_names[1:]
label_name = 0

In [0]:
batch_size = 64

training_dataset = tf.contrib.data.make_csv_dataset(dataset_file,batch_size,
                                                    column_names = column_names,
                                                    label_name = label_name,
                                                    shuffle_seed = 42,
                                                   num_epochs=1)

In [125]:
features, labels = next(iter(training_dataset))
features[1], 

(<tf.Tensor: id=36163, shape=(64,), dtype=int32, numpy=
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       dtype=int32)>,)

In [0]:
def pack_features_vector(features, labels):
  """Pack the features into a single array."""
  features = tf.cast(tf.stack(list(features.values()), axis=1),dtype=tf.float32)
  return features, labels

In [0]:
training_dataset = training_dataset.map(pack_features_vector)

In [156]:
#
features, labels = next(iter(training_dataset))
print(features)

tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(64, 784), dtype=float32)


##Model

In [0]:
# This returns a tensor
inputs = tf.keras.layers.Input(shape=(784,))

# a layer instance is callable on a tensor, and returns a tensor
x = tf.keras.layers.Dense(128, activation='relu',)(inputs)
x = tf.keras.layers.Dense(128, activation='relu')(x)
x = tf.keras.layers.Dense(64, activation='relu')(x)
x = tf.keras.layers.Dense(64, activation='relu')(x)
predictions = tf.keras.layers.Dense(10, activation='softmax')(x)

my_model = tf.keras.models.Model(inputs=inputs, outputs= predictions)

In [183]:
my_model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         (None, 784)               0         
_________________________________________________________________
dense_27 (Dense)             (None, 128)               100480    
_________________________________________________________________
dense_28 (Dense)             (None, 128)               16512     
_________________________________________________________________
dense_29 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_30 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_31 (Dense)             (None, 10)                650       
Total params: 130,058
Trainable params: 130,058
Non-trainable params: 0
_________________________________________________________________


In [0]:
def loss(model, features, labels):
  pred = model(features)
  return tf.losses.sparse_softmax_cross_entropy(labels=labels,logits=pred)
  

In [0]:
def gradient(model, features, labels):
  with tf.GradientTape() as tape:
    loss_value = loss(model, features, labels)
    gradient = tape.gradient(loss_value,model.trainable_variables)
    return loss_value, gradient

In [0]:
optimizer = tf.train.AdamOptimizer(learning_rate=0.01)
step = tf.Variable(0)

In [187]:

ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))
optimizer.apply_gradients(zip(gradients,my_model.trainable_variables),step)
ls, gradients = gradient(my_model, features, labels)
print("step: {}, loss: {}".format(step.numpy(), ls.numpy()))

step: 0, loss: 2.355208158493042
step: 1, loss: 2.3361501693725586


## Training loop